<div class="modal fade <?php echo $class ?>" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate($title) ?></h4>
            </div>
            <div class="modal-body">
                <?php echo $content ?>
            </div>
        </div>
    </div>
</div>